# Generated by Django 4.0 on 2021-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название мороженного')),
                ('ingridients', models.CharField(max_length=200, verbose_name='Ингридиенты в составе мороженного')),
                ('standart', models.CharField(max_length=30, verbose_name='Стандарт мороженного')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена мороженного')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Когда последний раз обновлялась информация?')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
