# Generated by Django 4.0 on 2021-12-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrchesraStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOrch', models.CharField(max_length=50, verbose_name='Название оркестра')),
                ('membersNum', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Количество участников')),
                ('dateCreation', models.DateTimeField(verbose_name='Дата формирования')),
            ],
        ),
        migrations.CreateModel(
            name='BatonistStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBat', models.CharField(max_length=30, verbose_name='Имя дирижера')),
                ('secondName', models.CharField(max_length=200, verbose_name='Фамилия дирижера')),
                ('age', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Возраст дирижера')),
                ('experience', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Стаж дирижера')),
                ('idOrch', models.ForeignKey(db_column='idOrch', on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.orchesrastock')),
            ],
        ),
    ]
